services:
  elastic:
    container_name: elastic
    image: bitnami/elasticsearch:latest
    privileged: true
    env_file: ${ENV_FILE}
    ports:
      - 9200:9200
    networks:
      general:
        aliases:
          - elastic

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail -u elastic:${ES_PASSWORD} localhost:9200/_cluster/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - "elastic_data:/bitnami/elasticsearch/data"
      - "elastic_plugins:/bitnami/elasticsearch/plugins"
      - "elastic_logs:/opt/bitnami/elasticsearch/logs"

    mem_limit: 2G
    memswap_limit: 4G

    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: 10

volumes:
  elastic_data:
    driver: local
  elastic_plugins:
    driver: local
  elastic_logs:
    driver: local

networks:
  general:
    name: ${NETWORK_NAME}
    external: true
